[package]
name = "resque"
version = "0.1.0"
authors = ["timglabisch <tim@ainfach.de>"]

[dependencies]
redis = "*"
chan-signal = "0.3"
chan = "0.1"
serde_derive = "1.0.*"
serde = "1.0.*"
serde_json = "1.0.*"
time = "*"
lazy_static = "*"
toml = "0.4"